---
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types

spec/spec_helper_acceptance.rb:
  unmanaged: false
  configure_beaker: ~

.github/CONTRIBUTING.md:
  delete: true
.github/ISSUE_TEMPLATE.md:
  delete: true
.github/PULL_REQUEST_TEMPLATE.md:
  delete: true
.github/SECURITY.md:
  delete: true
.github/workflows/shellcheck.yaml:
  delete: true
.github/workflows/markdownlint.yaml:
  delete: true

.github/workflows/ci.yml:
  with:
    beaker_hosts: master,replica,client
